--
-- Table structure for table `vb_user`
-- This table is the users' table of VBulletin (aka "VB"), the old forum used by the LSD.
-- It is used when migrating old users for example.
--

CREATE TABLE `vb_user`
(
    `userid`                            int(10) unsigned     NOT NULL AUTO_INCREMENT,
    `usergroupid`                       smallint(5) unsigned NOT NULL DEFAULT '0',
    `membergroupids`                    char(250)            NOT NULL DEFAULT '',
    `displaygroupid`                    smallint(5) unsigned NOT NULL DEFAULT '0',
    `username`                          varchar(100)         NOT NULL DEFAULT '',
    `passworddate`                      date                 NOT NULL DEFAULT '0000-00-00',
    `email`                             char(100)            NOT NULL DEFAULT '',
    `styleid`                           smallint(5) unsigned NOT NULL DEFAULT '0',
    `parentemail`                       char(50)             NOT NULL DEFAULT '',
    `homepage`                          char(100)            NOT NULL DEFAULT '',
    `icq`                               char(20)             NOT NULL DEFAULT '',
    `aim`                               char(20)             NOT NULL DEFAULT '',
    `yahoo`                             char(32)             NOT NULL DEFAULT '',
    `msn`                               char(100)            NOT NULL DEFAULT '',
    `skype`                             char(32)             NOT NULL DEFAULT '',
    `google`                            char(32)             NOT NULL DEFAULT '',
    `showvbcode`                        smallint(5) unsigned NOT NULL DEFAULT '0',
    `showbirthday`                      smallint(5) unsigned NOT NULL DEFAULT '2',
    `usertitle`                         char(250)            NOT NULL DEFAULT '',
    `customtitle`                       smallint(6)          NOT NULL DEFAULT '0',
    `joindate`                          int(10) unsigned     NOT NULL DEFAULT '0',
    `daysprune`                         smallint(6)          NOT NULL DEFAULT '0',
    `lastvisit`                         int(10) unsigned     NOT NULL DEFAULT '0',
    `lastactivity`                      int(10) unsigned     NOT NULL DEFAULT '0',
    `lastpost`                          int(10) unsigned     NOT NULL DEFAULT '0',
    `lastpostid`                        int(10) unsigned     NOT NULL DEFAULT '0',
    `posts`                             int(10) unsigned     NOT NULL DEFAULT '0',
    `reputation`                        int(11)              NOT NULL DEFAULT '10',
    `reputationlevelid`                 int(10) unsigned     NOT NULL DEFAULT '1',
    `timezoneoffset`                    char(4)              NOT NULL DEFAULT '',
    `pmpopup`                           smallint(6)          NOT NULL DEFAULT '0',
    `avatarid`                          smallint(6)          NOT NULL DEFAULT '0',
    `avatarrevision`                    int(10) unsigned     NOT NULL DEFAULT '0',
    `sigpicrevision`                    int(10) unsigned     NOT NULL DEFAULT '0',
    `options`                           int(10) unsigned     NOT NULL DEFAULT '167788559',
    `privacy_options`                   mediumtext,
    `notification_options`              int(10) unsigned     NOT NULL DEFAULT '1073741818',
    `birthday`                          char(10)             NOT NULL DEFAULT '',
    `birthday_search`                   date                 NOT NULL DEFAULT '0000-00-00',
    `maxposts`                          smallint(6)          NOT NULL DEFAULT '-1',
    `startofweek`                       smallint(6)          NOT NULL DEFAULT '1',
    `ipaddress`                         varchar(45)          NOT NULL DEFAULT '',
    `referrerid`                        int(10) unsigned     NOT NULL DEFAULT '0',
    `languageid`                        smallint(5) unsigned NOT NULL DEFAULT '0',
    `emailstamp`                        int(10) unsigned     NOT NULL DEFAULT '0',
    `threadedmode`                      smallint(5) unsigned NOT NULL DEFAULT '0',
    `emailnotification`                 smallint(5) unsigned NOT NULL DEFAULT '0',
    `pmtotal`                           smallint(5) unsigned NOT NULL DEFAULT '0',
    `pmunread`                          smallint(5) unsigned NOT NULL DEFAULT '0',
    `salt`                              char(30)             NOT NULL DEFAULT '',
    `ipoints`                           int(10) unsigned     NOT NULL DEFAULT '0',
    `infractions`                       int(10) unsigned     NOT NULL DEFAULT '0',
    `warnings`                          int(10) unsigned     NOT NULL DEFAULT '0',
    `infractiongroupids`                varchar(255)         NOT NULL DEFAULT '',
    `infractiongroupid`                 smallint(5) unsigned NOT NULL DEFAULT '0',
    `adminoptions`                      int(10) unsigned     NOT NULL DEFAULT '0',
    `profilevisits`                     int(10) unsigned     NOT NULL DEFAULT '0',
    `friendcount`                       int(10) unsigned     NOT NULL DEFAULT '0',
    `friendreqcount`                    int(10) unsigned     NOT NULL DEFAULT '0',
    `vmunreadcount`                     int(10) unsigned     NOT NULL DEFAULT '0',
    `vmmoderatedcount`                  int(10) unsigned     NOT NULL DEFAULT '0',
    `socgroupinvitecount`               int(10) unsigned     NOT NULL DEFAULT '0',
    `socgroupreqcount`                  int(10) unsigned     NOT NULL DEFAULT '0',
    `pcunreadcount`                     int(10) unsigned     NOT NULL DEFAULT '0',
    `pcmoderatedcount`                  int(10) unsigned     NOT NULL DEFAULT '0',
    `gmmoderatedcount`                  int(10) unsigned     NOT NULL DEFAULT '0',
    `assetposthash`                     varchar(32)          NOT NULL DEFAULT '',
    `fbuserid`                          varchar(255)         NOT NULL DEFAULT '',
    `fbjoindate`                        int(10) unsigned     NOT NULL DEFAULT '0',
    `fbname`                            varchar(255)         NOT NULL DEFAULT '',
    `token`                             varchar(255)         NOT NULL DEFAULT '',
    `scheme`                            varchar(100)         NOT NULL DEFAULT '',
    `secret`                            varchar(100)         NOT NULL DEFAULT '',
    `autosubscribe`                     smallint(5) unsigned NOT NULL DEFAULT '0',
    `privacyconsent`                    tinyint(4)           NOT NULL DEFAULT '0',
    `privacyconsentupdated`             int(10) unsigned     NOT NULL DEFAULT '0',
    `editorstate`                       int(10) unsigned     NOT NULL DEFAULT '1',
    `location`                          varchar(30)          NOT NULL DEFAULT 'UNKNOWN',
    `moderatornotificationoptions`      int(10) unsigned     NOT NULL DEFAULT '15',
    `moderatoremailnotificationoptions` int(10) unsigned     NOT NULL DEFAULT '0',
    PRIMARY KEY (`userid`),
    KEY `usergroupid` (`usergroupid`),
    KEY `username` (`username`),
    KEY `birthday` (`birthday`, `showbirthday`),
    KEY `birthday_search` (`birthday_search`),
    KEY `referrerid` (`referrerid`),
    KEY `fbuserid` (`fbuserid`),
    KEY `email` (`email`),
    KEY `joindate` (`joindate`),
    KEY `privacy_updated` (`privacyconsent`, `privacyconsentupdated`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
